// These styles apply to every route in the application
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>next</title>
      </head>
      <body>{children}</body>
    </html>
  );
}
